### PR TITLE
Avoid PHP error with BoilerplateComment and empty files

### LINKED ISSUE #97: moodle.Files.BoilerplateComment fails on empty files
Where a file has only an opening `<?php` tag, the BoilerplateComment sniff fails with the error message: An error occurred during processing; checking has been aborted. The error message was: Undefined array key 1 in /path/to/vendor/moodlehq/moodle-cs/moodle/Sniffs/Files/BoilerplateCommentSniff.php on line 78. The error originated in the moodle.Files.BoilerplateComment sniff on line 78

I would expect this not to fail but to let the user know that the copyright statement is missing.

You could argue that files like this shouldn't exist at all, but there are cases where they're necessary, for example moodle-plugin-ci's checks on plugins fail if lib.php is missing but there is often no need for any content in this.

### PR DESCRIPTION
**Pull request by stronk7**
Covered with a specific new test.

Fixes #97

### CODE REVIEW

File: moodle/Tests/FilesBoilerPlateCommentTest.php [hunk 1]
```diff
@@ -92,6 +92,19 @@ public function test_moodle_files_boilerplatecomment_short() {
         $this->verify_cs_results();
     }
 
+    public function test_moodle_files_boilerplatecomment_short_empty() {
+            $this->set_standard('moodle');
```
Comment (junpataleta) [inline moodle/Tests/FilesBoilerPlateCommentTest.php:96]: Thanks, @stronk7. This looks spot-on to me.  The indentation of this part seems to need some fixing, though.

**Review by junpataleta — CHANGES_REQUESTED** [review]

File: moodle/Tests/FilesBoilerPlateCommentTest.php (hunk 1 above)
Comment (stronk7) [reply moodle/Tests/FilesBoilerPlateCommentTest.php]: Whops, it should be fixed now. Thanks!

**Review by junpataleta — APPROVED** [review]
Thanks, @stronk7 ! Looking good now.
